### ISSUE TITLE
Make sample sheets programmatically

### ISSUE THREAD

**Issue by Loyale** [gofflab/scRNA_blank#1]
Make bam_files.txt, quant_files.txt programmatically in each script so that they carry over information from fastq_files.txt and do not need to be generated by hand at each stage.

Loyal

**Comment by eavincent** [comment]
I added 3 scripts, all "make_....sh" under the scripts directory that will make these files.  I modeled them after the original fastq_files.txt, bam_files.txt and quant_files.txt in Chakravarti_HD_01, but they can be modified to include more columns/cell info.  Currently pulling from file names in the data/bam folder for the bam and quant sample sheets but can (and likely will) also be edited to pull from fastq_files.txt.

**Comment by eavincent** [comment]
Done and committed.

**Comment by Loyale** [comment]
Amazing! Thank you.
